include themes/kanagawa.conf

font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13
# modify_font cell_height 160%
# modify_font strikethrough_position 7
# modify_font underline_position 2
modify_font strikethrough_thickness 150%
modify_font underline_thickness 250%

cursor_shape block
cursor_trail 3

mouse_hide_wait 1.0

enable_audio_bell no

url_style dashed
detect_urls no
underline_hyperlinks never

shell_integration enabled
paste_actions replace-dangerous-control-codes,replace-newline,confirm,quote-urls-at-prompt

window_border_width 1.0
window_margin_width 0
window_padding_width 0
placement_strategy bottom

enabled_layouts splits

tab_bar_min_tabs 2
tab_bar_style custom
tab_separator " "
tab_title_template " {index} {title}{activity_symbol} "
tab_activity_symbol *
tab_bar_edge bottom

startup_session local.session

clear_all_shortcuts yes

allow_remote_control no

include ${KITTY_OS}.conf
