hide_window_decorations yes

wayland_titlebar_color #1c1c1c

background_opacity 0.85
background_blur 5

map --new-mode prefix --on-action end --on-unknown end ctrl+shift+x

map --mode prefix r load_config_file
map --mode prefix ctrl+shift+r load_config_file
map --mode prefix ctrl+shift+u show_scrollback
map --mode prefix q quit
map --mode prefix ? command_palette

map --mode prefix r start_resizing_window
map --mode prefix x close_window_with_confirmation ignore-shell
map --mode prefix 1 goto_tab 1
map --mode prefix 2 goto_tab 2
map --mode prefix 3 goto_tab 3
map --mode prefix 4 goto_tab 4
map --mode prefix 5 goto_tab 5
map --mode prefix 6 goto_tab 6
map --mode prefix 7 goto_tab 7
map --mode prefix 8 goto_tab 8
map --mode prefix 9 goto_tab 9
map --mode prefix 0 goto_tab 10
map --mode prefix , launch --type=overlay --title=current --allow-remote-control ~/.config/kitty/rename_tab.sh
map --mode prefix o launch --type=overlay --title=current --allow-remote-control ~/.config/kitty/search_tab.sh
map --mode prefix c launch --type=tab --location=after
map --mode prefix n next_tab
map --mode prefix p previous_tab
map --mode prefix ctrl+shift+n next_tab
map --mode prefix ctrl+shift+p previous_tab
map --mode prefix a goto_tab 0
map --mode prefix ctrl+shift+a goto_tab 0
map --mode prefix shift+h move_tab_backward
map --mode prefix shift+l move_tab_backward
map --mode prefix h neighboring_window left
map --mode prefix l neighboring_window right
map --mode prefix j neighboring_window down
map --mode prefix k neighboring_window up
map --mode prefix ctrl+shift+h neighboring_window left
map --mode prefix ctrl+shift+l neighboring_window right
map --mode prefix ctrl+shift+j neighboring_window down
map --mode prefix ctrl+shift+k neighboring_window up
map --mode prefix v launch --type=window --location=vsplit
map --mode prefix s launch --type=window --location=hsplit

map --mode prefix f toggle_fullscreen
map --mode prefix m toggle_maximized

map --mode prefix plus change_font_size all +2.0
map --mode prefix kp_add change_font_size all +2.0
map --mode prefix minus change_font_size all -2.0
map --mode prefix kp_subtract change_font_size all -2.0
map --mode prefix backspace change_font_size all 0

map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_and_clear_or_interrupt
