screenshot-directory=~/Pictures/Screenshots
screenshot-template="%F (%wH:%wM:%wS) %02n"
screenshot-jpeg-quality=100

# https://github.com/tomasklaen/uosc
# https://github.com/po5/thumbfast
osd-bar=no
border=no
