[mgr]
ratio = [1, 2, 3]
sort_by = "mtime"
sort_sensitive = true
sort_reverse = true
sort_dir_first = false
linemode = "mtime"
show_hidden = true
show_symlink = true
mouse_events = []
title_format = "{cwd}"
scrolloff = 5

[preview]
max_width = 2160
image_filter = "triangle"
image_quality = 90

[opener]
play = [
	{ run = "mpv %s", orphan = true },
]

[open]

[input]
cursor_blink = false
