add_newline = true
format = "$jobs${custom.fish_private}${custom.icon}$hostname$directory$cmd_duration$status${custom.yazi}${custom.temp} "
right_format = "$time$git_status$git_branch"
command_timeout = 2000

[time]
format = "[ $time ](bg:black fg:bright-white)"
use_12hr = true
time_format = '%I:%M %P'
disabled = false

[status]
format = "[ $status ](bg:black fg:red)"
disabled = false

[cmd_duration]
format = "[ $duration ](bg:blue fg:bright-black)"
disabled = false
min_time = 3000

[directory]
format = "[ $path ](bg:bright-black fg:bright-white)"

[hostname]
format = "[ $hostname ](bg:black fg:bright-white)"
ssh_only = false

[username]
show_always = true
format = "$user"

[git_branch]
format = "[ $branch ](bg:bright-black fg:bright-white)"
symbol = "GIT"

[git_status]
conflicted = " *"
ahead = " *"
behind = " *"
diverged = " *"
up_to_date = ""
untracked = " *"
stashed = " ◯"
modified = " *"
staged = " *"
renamed = " *"
deleted = " *"
format = "[$all_status](bg:bright-black fg:red)"

[jobs]
format = "[ $symbol $number ](bg:purple fg:bright-black)"
number_threshold = 1
symbol_threshold = 1

[custom.icon]
format = "[ λ ](bg:bright-black fg:yellow)"
when = 'test -z "$fish_private_mode"'

[custom.fish_private]
format = "[ λ ](bg:yellow fg:bright-black)"
when = 'test -n "$fish_private_mode"'

[custom.yazi]
format = "[ 󰇥 ](bg:yellow fg:black)"
when = 'test -n "$__YAZI_OPEN"'

[custom.temp]
format = "[ TEMP ](bg:purple fg:black)"
when = 'test -n "$__TEMPDO"'
